### ISSUE TITLE
Possible Typo in User Guide

### ISSUE THREAD

**Issue by Javaru** [keyboardio/Model01-Legends#7]
It might just be a case of me being overly pedantic, but... I noticed the very last line in the "Model 01 Quick Start Guide" (as of commit c53dbc02e3a058cfd2734164d69a0e3c5876b0b9) states "Copyright 2017 Keyboard.io, Inc." On the Keyboardio website, under [branding guidelines](https://shop.keyboard.io/pages/press-kit#branding-guidelines), it states: 

> Our website is http://keyboard.io, but the company name does not have dots in it.

Was it intended that the copyright statement in the user guide have the dot in the company name? If it is an error, I thought you might be able to fix it prior to the main production run.

**Comment by obra** [comment]
The -legal- name of the company has a . 

We don't use it anywhere except in a legal context.

**Comment by Javaru** [comment]
Gotcha.  Thanks. Good luck with the production run.
