### ISSUE TITLE
Please add an empty legend

### ISSUE THREAD

**Issue by tarsius** [keyboardio/Model01-Legends#8]
I wasn't able to find a file that contained an empty legend like on the back of the laminated legends that shipped with the keyboard. Could you please add that?

For the time being I am just going to photocopy. That actually looks surprisingly good despite the lamination and how I had to place the original on the scanner.

**Comment by Jennigma** [comment]
@TheBaronHimself - Do you have this handy? :-)

**Comment by TheBaronHimself** [comment]
There you go :).


[2017-11-05--model-01-layout-card-001.pdf](https://github.com/keyboardio/Model01-Legends/files/1444114/2017-11-05--model-01-layout-card-001.pdf)

**Comment by TheBaronHimself** [comment]
Here you go :).

[2017-11-05--model-01-layout-card-001.pdf](https://github.com/keyboardio/Model01-Legends/files/1444117/2017-11-05--model-01-layout-card-001.pdf)

**Comment by Jennigma** [comment]
Ah! it was there all along! 

https://github.com/keyboardio/Model01-Legends/tree/master/layout_card

I should probably link these from the wiki, but that closes this issue, I think. :-)

**Comment by algernon** [comment]
I think the blank layout should be added to the repo too, makes it easier to find.

@TheBaronHimself can you submit a PR with the blank layout card?

**Comment by tarsius** [comment]
Thanks by the way :wink:

**Comment by TheBaronHimself** [comment]
https://github.com/keyboardio/Model01-Legends/pull/9

**Comment by tarsius** [comment]
Thanks again!
